#!/usr/bin/env python3
"""Prepare deterministic output paths for Zotero group-meeting notes.

This script intentionally handles only mechanical filesystem work:
filename sanitization, default directory creation, optional note stubs,
and asset copying. The note body should still be generated by Codex.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
from datetime import date, datetime
from pathlib import Path
from typing import Iterable


NOTE_TITLE_PREFIX = "组会分享笔记："
DEFAULT_OBSIDIAN_VAULT = Path(
    os.environ.get(
        "ZOTERO_GROUP_MEETING_OBSIDIAN_VAULT",
        str(Path.home() / "Documents" / "Obsidian Vault"),
    )
)
INVALID_WINDOWS_CHARS = '<>:"/\\|?*'
COMMON_DOCUMENT_EXTENSIONS = {
    ".pdf",
    ".md",
    ".markdown",
    ".html",
    ".htm",
    ".docx",
    ".doc",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create deterministic Zotero-compatible and Obsidian output paths."
    )
    parser.add_argument(
        "--article-filename",
        required=True,
        help="Paper title or attachment filename used to derive the default note filename.",
    )
    parser.add_argument(
        "--note-filename",
        help="Custom Markdown filename, with or without .md. Defaults to <paper title>.md.",
    )
    parser.add_argument(
        "--note-title",
        help="Custom H1 note title. Defaults to 组会分享笔记：<paper title>.",
    )
    parser.add_argument(
        "--date",
        help="Request date. Accepts YYYY-MM-DD or yy-M-d. Defaults to today.",
    )
    parser.add_argument(
        "--current-dir",
        default=".",
        help="Folder for the Zotero-compatible Markdown file. Defaults to current directory.",
    )
    parser.add_argument(
        "--zotero-note-path",
        help="Exact Zotero-compatible Markdown file path. Overrides --current-dir and --note-filename.",
    )
    parser.add_argument(
        "--obsidian-vault",
        default=str(DEFAULT_OBSIDIAN_VAULT),
        help=(
            "Obsidian vault root. Defaults to env ZOTERO_GROUP_MEETING_OBSIDIAN_VAULT "
            "or ~/Documents/Obsidian Vault."
        ),
    )
    parser.add_argument(
        "--obsidian-dir",
        help="Exact Obsidian output folder. Overrides --obsidian-vault and --date.",
    )
    parser.add_argument(
        "--obsidian-note-path",
        help="Exact Obsidian Markdown file path. Overrides --obsidian-dir, --obsidian-vault, --date, and --note-filename.",
    )
    parser.add_argument(
        "--no-title-prefix",
        action="store_true",
        help="Use the paper title as the H1 note title instead of prefixing 组会分享笔记：.",
    )
    parser.add_argument(
        "--keep-extension",
        action="store_true",
        help="Keep a document extension such as .pdf in the note filename.",
    )
    parser.add_argument(
        "--no-zotero-file",
        action="store_true",
        help="Do not create the current-folder Zotero-compatible target path.",
    )
    parser.add_argument(
        "--no-obsidian",
        action="store_true",
        help="Do not create the default Obsidian vault/date/assets folders.",
    )
    parser.add_argument(
        "--asset",
        action="append",
        default=[],
        help="Asset file to copy into the Obsidian assets folder. Can be repeated.",
    )
    parser.add_argument(
        "--asset-dir",
        action="append",
        default=[],
        help="Directory whose immediate files should be copied into the Obsidian assets folder.",
    )
    parser.add_argument(
        "--create-note-stubs",
        action="store_true",
        help="Create Markdown files containing only the H1 title if they do not exist.",
    )
    parser.add_argument(
        "--overwrite-stubs",
        action="store_true",
        help="Overwrite existing note files when --create-note-stubs is used.",
    )
    return parser.parse_args()


def normalize_date(value: str | None) -> str:
    if not value:
        today = date.today()
        return f"{today.year % 100}-{today.month}-{today.day}"

    value = value.strip()
    for fmt in ("%Y-%m-%d", "%y-%m-%d"):
        try:
            parsed = datetime.strptime(value, fmt)
            return f"{parsed.year % 100}-{parsed.month}-{parsed.day}"
        except ValueError:
            pass

    parts = value.split("-")
    if len(parts) == 3 and all(part.isdigit() for part in parts):
        year, month, day = (int(part) for part in parts)
        if year >= 2000:
            year = year % 100
        return f"{year}-{month}-{day}"

    raise ValueError("Date must be YYYY-MM-DD or yy-M-d.")


def article_base_name(article_filename: str, keep_extension: bool) -> str:
    stripped = article_filename.strip()
    looks_like_path = (
        Path(stripped).expanduser().exists()
        or bool(re.match(r"^[A-Za-z]:[\\/]", stripped))
        or stripped.startswith(("\\\\", "/", "~"))
    )
    name = re.split(r"[\\/]+", stripped)[-1] if looks_like_path else stripped
    stem, suffix = os.path.splitext(name)
    if not keep_extension and suffix.lower() in COMMON_DOCUMENT_EXTENSIONS:
        name = stem
    return name or "未命名论文"


def sanitize_filename_part(value: str, max_chars: int = 140) -> str:
    cleaned = "".join("-" if char in INVALID_WINDOWS_CHARS else char for char in value)
    cleaned = " ".join(cleaned.split()).strip(" .")
    cleaned = cleaned or "未命名论文"

    if len(cleaned) <= max_chars:
        return cleaned

    digest = hashlib.sha1(cleaned.encode("utf-8")).hexdigest()[:8]
    return f"{cleaned[:max_chars].rstrip()}-{digest}"


def normalize_note_filename(value: str | None, default_stem: str) -> str:
    raw = value.strip() if value else default_stem
    if raw.lower().endswith(".md"):
        raw = raw[:-3]
    return f"{sanitize_filename_part(raw)}.md"


def normalize_markdown_path(value: str) -> Path:
    path = Path(value).expanduser()
    if path.suffix.lower() != ".md":
        path = path.with_suffix(".md")
    return path.resolve()


def unique_destination(destination: Path) -> Path:
    if not destination.exists():
        return destination

    stem = destination.stem
    suffix = destination.suffix
    parent = destination.parent
    counter = 2
    while True:
        candidate = parent / f"{stem}-{counter}{suffix}"
        if not candidate.exists():
            return candidate
        counter += 1


def iter_asset_files(files: Iterable[str], dirs: Iterable[str]) -> list[Path]:
    result: list[Path] = []

    for item in files:
        path = Path(item).expanduser().resolve()
        if path.is_file():
            result.append(path)

    for item in dirs:
        path = Path(item).expanduser().resolve()
        if path.is_dir():
            result.extend(child for child in sorted(path.iterdir()) if child.is_file())

    return result


def copy_assets(asset_files: list[Path], assets_dir: Path) -> list[dict[str, str]]:
    copied: list[dict[str, str]] = []
    assets_dir.mkdir(parents=True, exist_ok=True)

    for source in asset_files:
        safe_name = sanitize_filename_part(source.stem, max_chars=70) + source.suffix.lower()
        destination = unique_destination(assets_dir / safe_name)
        shutil.copy2(source, destination)
        copied.append(
            {
                "source": str(source),
                "destination": str(destination),
                "markdown": f"assets/{destination.name}",
            }
        )

    return copied


def maybe_create_stub(path: Path, title: str, create: bool, overwrite: bool) -> bool:
    if not create:
        return False
    if path.exists() and not overwrite:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"# {title}\n", encoding="utf-8")
    return True


def main() -> int:
    args = parse_args()

    request_date = normalize_date(args.date)
    article_name = article_base_name(args.article_filename, args.keep_extension)
    safe_article_name = sanitize_filename_part(article_name)
    note_title = (
        args.note_title.strip()
        if args.note_title
        else safe_article_name
        if args.no_title_prefix
        else f"{NOTE_TITLE_PREFIX}{safe_article_name}"
    )
    note_filename = normalize_note_filename(args.note_filename, article_name)

    current_dir = Path(args.current_dir).expanduser().resolve()

    zotero_note_path = None
    zotero_stub_created = False
    if not args.no_zotero_file:
        if args.zotero_note_path:
            zotero_note_path = normalize_markdown_path(args.zotero_note_path)
        else:
            current_dir.mkdir(parents=True, exist_ok=True)
            zotero_note_path = current_dir / note_filename
        zotero_stub_created = maybe_create_stub(
            zotero_note_path, note_title, args.create_note_stubs, args.overwrite_stubs
        )

    obsidian_note_path = None
    obsidian_assets_dir = None
    copied_assets: list[dict[str, str]] = []
    obsidian_stub_created = False
    if not args.no_obsidian:
        if args.obsidian_note_path:
            obsidian_note_path = normalize_markdown_path(args.obsidian_note_path)
            obsidian_date_dir = obsidian_note_path.parent
            obsidian_vault = None
        elif args.obsidian_dir:
            obsidian_date_dir = Path(args.obsidian_dir).expanduser().resolve()
            obsidian_vault = None
        else:
            obsidian_vault = Path(args.obsidian_vault).expanduser().resolve()
            obsidian_date_dir = obsidian_vault / "组会分享" / request_date
        obsidian_assets_dir = obsidian_date_dir / "assets"
        obsidian_assets_dir.mkdir(parents=True, exist_ok=True)
        if obsidian_note_path is None:
            obsidian_note_path = obsidian_date_dir / note_filename
        obsidian_stub_created = maybe_create_stub(
            obsidian_note_path, note_title, args.create_note_stubs, args.overwrite_stubs
        )
        copied_assets = copy_assets(
            iter_asset_files(args.asset, args.asset_dir), obsidian_assets_dir
        )

    result = {
        "note_title": note_title,
        "note_filename": note_filename,
        "request_date": request_date,
        "paper_name": safe_article_name,
        "zotero_note_path": str(zotero_note_path) if zotero_note_path else None,
        "zotero_stub_created": zotero_stub_created,
        "obsidian_vault": str(obsidian_vault) if not args.no_obsidian and obsidian_vault else None,
        "obsidian_output_dir": str(obsidian_note_path.parent) if obsidian_note_path else None,
        "obsidian_note_path": str(obsidian_note_path) if obsidian_note_path else None,
        "obsidian_assets_dir": str(obsidian_assets_dir) if obsidian_assets_dir else None,
        "obsidian_stub_created": obsidian_stub_created,
        "copied_assets": copied_assets,
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
