#!/usr/bin/env python3
"""Prepare deterministic output paths for Zotero group-meeting notes.

This script intentionally handles only mechanical filesystem work:
filename sanitization, default directory creation, optional note stubs,
and asset copying. The note body should still be generated by Codex.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Any, Iterable


NOTE_TITLE_PREFIX = "组会分享笔记："
DEFAULT_OBSIDIAN_VAULT = Path(
    os.environ.get(
        "ZOTERO_GROUP_MEETING_OBSIDIAN_VAULT",
        str(Path.home() / "Documents" / "Obsidian Vault"),
    )
)
INVALID_WINDOWS_CHARS = '<>:"/\\|?*'
COMMON_DOCUMENT_EXTENSIONS = {
    ".pdf",
    ".md",
    ".markdown",
    ".html",
    ".htm",
    ".docx",
    ".doc",
}

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create deterministic Zotero-compatible and Obsidian output paths."
    )
    parser.add_argument(
        "--article-filename",
        required=True,
        help="Paper title or attachment filename used to derive the default note filename.",
    )
    parser.add_argument(
        "--note-filename",
        help="Custom Markdown filename, with or without .md. Defaults to <paper title>.md.",
    )
    parser.add_argument(
        "--note-title",
        help="Custom H1 note title. Defaults to 组会分享笔记：<paper title>.",
    )
    parser.add_argument(
        "--date",
        help="Request date. Accepts YYYY-MM-DD or yy-M-d. Defaults to today.",
    )
    parser.add_argument(
        "--current-dir",
        default=".",
        help="Folder for the Zotero-compatible Markdown file. Defaults to current directory.",
    )
    parser.add_argument(
        "--zotero-note-path",
        help="Exact Zotero-compatible Markdown file path. Overrides --current-dir and --note-filename.",
    )
    parser.add_argument(
        "--obsidian-vault",
        default=str(DEFAULT_OBSIDIAN_VAULT),
        help=(
            "Obsidian vault root. Defaults to env ZOTERO_GROUP_MEETING_OBSIDIAN_VAULT "
            "or ~/Documents/Obsidian Vault."
        ),
    )
    parser.add_argument(
        "--obsidian-dir",
        help="Exact Obsidian output folder. Overrides --obsidian-vault and --date.",
    )
    parser.add_argument(
        "--obsidian-note-path",
        help="Exact Obsidian Markdown file path. Overrides --obsidian-dir, --obsidian-vault, --date, and --note-filename.",
    )
    parser.add_argument(
        "--no-title-prefix",
        action="store_true",
        help="Use the paper title as the H1 note title instead of prefixing 组会分享笔记：.",
    )
    parser.add_argument(
        "--keep-extension",
        action="store_true",
        help="Keep a document extension such as .pdf in the note filename.",
    )
    parser.add_argument(
        "--no-zotero-file",
        action="store_true",
        help="Do not create the current-folder Zotero-compatible target path.",
    )
    parser.add_argument(
        "--no-obsidian",
        action="store_true",
        help="Do not create the default Obsidian vault/date/assets folders.",
    )
    parser.add_argument(
        "--asset",
        action="append",
        default=[],
        help="Asset file to copy into the Obsidian assets folder. Can be repeated.",
    )
    parser.add_argument(
        "--asset-dir",
        action="append",
        default=[],
        help="Directory whose immediate files should be copied into the Obsidian assets folder.",
    )
    parser.add_argument(
        "--create-note-stubs",
        action="store_true",
        help="Create Markdown files containing only the H1 title if they do not exist.",
    )
    parser.add_argument(
        "--overwrite-stubs",
        action="store_true",
        help="Overwrite existing note files when --create-note-stubs is used.",
    )
    parser.add_argument(
        "--sync-from-manifest",
        help="Evidence manifest JSON from build_evidence_manifest.py. "
        "Auto-copies all high/medium-confidence matched assets into the Obsidian assets folder "
        "with readable filenames derived from evidence labels.",
    )
    parser.add_argument(
        "--copy-map",
        help="Optional JSON path for the manifest asset copy map used by drafting/validation.",
    )
    return parser.parse_args()


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8-sig", errors="ignore"))


def normalize_date(value: str | None) -> str:
    if not value:
        today = date.today()
        return f"{today.year % 100}-{today.month}-{today.day}"

    value = value.strip()
    for fmt in ("%Y-%m-%d", "%y-%m-%d"):
        try:
            parsed = datetime.strptime(value, fmt)
            return f"{parsed.year % 100}-{parsed.month}-{parsed.day}"
        except ValueError:
            pass

    parts = value.split("-")
    if len(parts) == 3 and all(part.isdigit() for part in parts):
        year, month, day = (int(part) for part in parts)
        if year >= 2000:
            year = year % 100
        return f"{year}-{month}-{day}"

    raise ValueError("Date must be YYYY-MM-DD or yy-M-d.")


def article_base_name(article_filename: str, keep_extension: bool) -> str:
    stripped = article_filename.strip()
    looks_like_path = (
        Path(stripped).expanduser().exists()
        or bool(re.match(r"^[A-Za-z]:[\\/]", stripped))
        or stripped.startswith(("\\\\", "/", "~"))
    )
    name = re.split(r"[\\/]+", stripped)[-1] if looks_like_path else stripped
    stem, suffix = os.path.splitext(name)
    if not keep_extension and suffix.lower() in COMMON_DOCUMENT_EXTENSIONS:
        name = stem
    return name or "未命名论文"


def sanitize_filename_part(value: str, max_chars: int = 140) -> str:
    cleaned = "".join("-" if char in INVALID_WINDOWS_CHARS else char for char in value)
    cleaned = " ".join(cleaned.split()).strip(" .")
    cleaned = cleaned or "未命名论文"

    if len(cleaned) <= max_chars:
        return cleaned

    digest = hashlib.sha1(cleaned.encode("utf-8")).hexdigest()[:8]
    return f"{cleaned[:max_chars].rstrip()}-{digest}"


ASSET_KIND_ALIASES = {
    "fig": "figure",
    "figure": "figure",
    "tab": "table",
    "table": "table",
    "eq": "equation",
    "equation": "equation",
    "formula": "formula",
    "alg": "algorithm",
    "algorithm": "algorithm",
}

ASSET_LABEL_RE = re.compile(
    r"\b(?P<supp>supplementary|appendix|supp\.?)?\s*"
    r"(?P<kind>figure|fig\.?|table|tab\.?|equation|eq\.?|formula|algorithm|alg\.?)"
    r"\s*(?P<number>[A-Za-z]?\d+[A-Za-z]?)\b",
    re.IGNORECASE,
)

ASSET_TOPIC_STOPWORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "for",
    "from",
    "in",
    "into",
    "is",
    "it",
    "left",
    "of",
    "on",
    "or",
    "our",
    "right",
    "that",
    "the",
    "their",
    "this",
    "to",
    "vs",
    "with",
}

PAPER_TOKEN_STOPWORDS = {
    "a",
    "an",
    "and",
    "for",
    "from",
    "in",
    "of",
    "on",
    "the",
    "to",
    "toward",
    "towards",
    "via",
    "with",
}


def slug_words(
    text: str,
    *,
    max_words: int = 5,
    max_chars: int = 48,
    stopwords: set[str] | None = None,
    exclude: set[str] | None = None,
) -> str:
    words = [word.lower() for word in re.findall(r"[A-Za-z0-9]+", text)]
    stop = stopwords or set()
    excluded = exclude or set()
    kept: list[str] = []
    for word in words:
        if len(word) <= 1 or word in stop or word in excluded:
            continue
        kept.append(word)
        if len(kept) >= max_words:
            break
    slug = "-".join(kept) or "evidence"
    if len(slug) <= max_chars:
        return slug
    trimmed = slug[:max_chars].strip("-")
    return trimmed or "evidence"


def paper_token_from_article(article_name: str) -> str:
    name = article_base_name(article_name, keep_extension=False)
    acronym = re.match(r"\s*([A-Za-z][A-Za-z0-9]{1,15})(?=\s*[:：\-–—])", name)
    if acronym:
        return acronym.group(1).lower()
    return slug_words(
        name,
        max_words=2,
        max_chars=28,
        stopwords=PAPER_TOKEN_STOPWORDS,
    )


def normalize_asset_label(label_text: str, item_type: str, order: object | None) -> tuple[str, str, bool]:
    match = ASSET_LABEL_RE.search(label_text)
    is_supp = False
    if match:
        kind_key = match.group("kind").lower().rstrip(".")
        kind = ASSET_KIND_ALIASES.get(kind_key, kind_key)
        raw_number = match.group("number")
        is_supp = bool(match.group("supp"))
    else:
        kind_key = item_type.lower().rstrip(".")
        kind = ASSET_KIND_ALIASES.get(kind_key, kind_key or "evidence")
        raw_number = str(order or "").strip()

    if raw_number.isdigit():
        number = f"{int(raw_number):02d}"
    else:
        number = slug_words(raw_number, max_words=1, max_chars=12) if raw_number else "xx"
    return kind, number, is_supp


def label_without_prefix(text: str, label_text: str) -> str:
    if not text:
        return ""

    label_match = ASSET_LABEL_RE.search(text)
    if label_match:
        return text[label_match.end() :].lstrip(" :-—–.").strip()

    if label_text and text.lower().startswith(label_text.lower()):
        return text[len(label_text) :].lstrip(" :-—–.").strip()

    return text.strip()


def topic_text_from_manifest_item(item: dict[str, Any]) -> str:
    payload = item.get("content_payload")
    candidates: list[str] = []
    if isinstance(payload, dict):
        for key in ("image_caption", "table_caption", "caption", "text", "content"):
            value = payload.get(key)
            if isinstance(value, str) and value.strip():
                candidates.append(value)
    for key in ("caption_or_nearby_text", "source_text", "section", "label"):
        value = item.get(key)
        if isinstance(value, str) and value.strip():
            candidates.append(value)
    return candidates[0] if candidates else str(item.get("label", "evidence"))


def asset_stem_from_manifest_item(
    item: dict[str, Any],
    article_name: str,
    asset_index: int,
    asset_count: int,
) -> str:
    label_text = str(item.get("label", "unnamed"))
    item_type = str(item.get("type", "evidence"))
    kind, number, label_is_supp = normalize_asset_label(label_text, item_type, item.get("order"))
    paper_token = paper_token_from_article(article_name)
    region = str(item.get("region", "main")).lower()
    is_supp = label_is_supp or region in {"post_reference", "appendix", "supplement", "supplementary"}

    raw_topic = label_without_prefix(topic_text_from_manifest_item(item), label_text)
    topic = slug_words(
        raw_topic,
        max_words=5,
        max_chars=48,
        stopwords=ASSET_TOPIC_STOPWORDS,
        exclude=set(paper_token.split("-")),
    )
    parts = [kind, number, paper_token]
    if is_supp:
        parts.append("supp")
    parts.append(topic)
    if asset_count > 1:
        parts.append(f"panel-{asset_index:02d}")
    return sanitize_filename_part("-".join(parts), max_chars=90)


def normalize_note_filename(value: str | None, default_stem: str) -> str:
    raw = value.strip() if value else default_stem
    if raw.lower().endswith(".md"):
        raw = raw[:-3]
    return f"{sanitize_filename_part(raw)}.md"


def normalize_markdown_path(value: str) -> Path:
    path = Path(value).expanduser()
    if path.suffix.lower() != ".md":
        path = path.with_suffix(".md")
    return path.resolve()


def unique_destination(destination: Path) -> Path:
    if not destination.exists():
        return destination

    stem = destination.stem
    suffix = destination.suffix
    parent = destination.parent
    counter = 2
    while True:
        candidate = parent / f"{stem}-{counter}{suffix}"
        if not candidate.exists():
            return candidate
        counter += 1


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def existing_asset_by_hash(
    assets_dir: Path, source_hash: str, preferred_stem: str | None = None
) -> Path | None:
    if not source_hash or not assets_dir.is_dir():
        return None
    for candidate in sorted(assets_dir.iterdir()):
        if not candidate.is_file():
            continue
        if preferred_stem and not (
            candidate.stem == preferred_stem or candidate.stem.startswith(f"{preferred_stem}-")
        ):
            continue
        try:
            if file_sha256(candidate) == source_hash:
                return candidate
        except OSError:
            continue
    return None


def iter_asset_files(files: Iterable[str], dirs: Iterable[str]) -> list[Path]:
    result: list[Path] = []

    for item in files:
        path = Path(item).expanduser().resolve()
        if path.is_file():
            result.append(path)

    for item in dirs:
        path = Path(item).expanduser().resolve()
        if path.is_dir():
            result.extend(child for child in sorted(path.iterdir()) if child.is_file())

    return result


def copy_assets(asset_files: list[Path], assets_dir: Path) -> list[dict[str, str]]:
    copied: list[dict[str, str]] = []
    assets_dir.mkdir(parents=True, exist_ok=True)

    for source in asset_files:
        safe_name = sanitize_filename_part(source.stem, max_chars=70) + source.suffix.lower()
        source_hash = file_sha256(source)
        preferred_stem = Path(safe_name).stem
        destination = existing_asset_by_hash(assets_dir, source_hash, preferred_stem)
        copy_action = "reused" if destination else "copied"
        if destination is None:
            destination = unique_destination(assets_dir / safe_name)
            shutil.copy2(source, destination)
        copied.append(
            {
                "source": str(source),
                "destination": str(destination),
                "markdown": f"assets/{destination.name}",
                "source_sha256": source_hash,
                "destination_sha256": file_sha256(destination),
                "copy_action": copy_action,
            }
        )

    return copied


def resolve_manifest_asset_path(raw_path: object, manifest_data: dict[str, Any], manifest_dir: Path) -> Path:
    path_text = str(raw_path).strip().strip("<>")
    path_text = path_text.split("#", 1)[0].split("?", 1)[0].replace("\\", "/")
    path = Path(path_text)
    if path.is_absolute():
        return path.resolve()

    source_info = manifest_data.get("source", {})
    assets_root_text = str(source_info.get("assets_dir", "")).strip() if isinstance(source_info, dict) else ""
    candidates: list[Path] = []
    if assets_root_text:
        assets_root = Path(assets_root_text).expanduser()
        candidates.extend(
            [
                assets_root / path_text,
                assets_root / path.name,
                assets_root.parent / path_text,
                assets_root.parent / path.name,
            ]
        )
    candidates.extend([manifest_dir / path_text, manifest_dir / path.name])
    for candidate in candidates:
        resolved = candidate.resolve()
        if resolved.is_file():
            return resolved
    if candidates:
        return candidates[0].resolve()
    return path.resolve()


def sync_assets_from_manifest(manifest_path: str, assets_dir: Path, article_name: str) -> list[dict[str, str]]:
    """Copy high/medium-confidence matched assets from a manifest into the assets dir.

    Files are renamed as kind-number-paper-topic stems such as
    ``figure-01-skcc-workflow-complexity.jpg``. Conflicts are resolved by
    appending a counter.
    """
    copied: list[dict[str, str]] = []
    manifest_file = Path(manifest_path).expanduser().resolve()
    manifest_data = read_json(manifest_file)
    manifest_dir = manifest_file.parent
    items = manifest_data.get("items") or []
    if "main_items" in manifest_data or "post_reference_items" in manifest_data:
        items = manifest_data.get("main_items", []) + manifest_data.get("post_reference_items", [])

    for item in items:
        conf = item.get("match_confidence", "low")
        if conf not in {"high", "medium"}:
            continue
        asset_paths = item.get("asset_paths") or []
        if item.get("matched_asset"):
            asset_paths = [item["matched_asset"]] + [p for p in asset_paths if p != item["matched_asset"]]
        if not asset_paths:
            continue

        label_text = item.get("label", "unnamed")
        item_type = str(item.get("type", "evidence")).lower()
        label_key = str(label_text).lower().replace(" ", "-")
        item_key = str(item.get("item_key") or f"{item_type}-{label_key}")
        for asset_index, matched in enumerate(asset_paths, start=1):
            source = resolve_manifest_asset_path(matched, manifest_data, manifest_dir)
            if not source.is_file():
                continue

            suffix = source.suffix.lower()
            safe_stem = asset_stem_from_manifest_item(
                item,
                article_name,
                asset_index,
                len(asset_paths),
            )
            source_hash = file_sha256(source)
            destination = existing_asset_by_hash(assets_dir, source_hash, safe_stem)
            copy_action = "reused" if destination else "copied"
            if destination is None:
                destination = unique_destination(assets_dir / f"{safe_stem}{suffix}")
                shutil.copy2(source, destination)
            destination_hash = file_sha256(destination)
            copied.append(
                {
                    "item_key": item_key,
                    "source": str(source),
                    "destination": str(destination),
                    "markdown": f"assets/{destination.name}",
                    "source_sha256": source_hash,
                    "destination_sha256": destination_hash,
                    "label": str(label_text),
                    "confidence": conf,
                    "region": item.get("region", "main"),
                    "block_index": str(item.get("block_index", "")),
                    "page": str(item.get("page", "")),
                    "asset_index": str(asset_index),
                    "copy_action": copy_action,
                }
            )

    return copied


def write_copy_map(path: str, manifest_path: str | None, assets_dir: Path | None, copied_assets: list[dict[str, str]]) -> None:
    output_path = Path(path).expanduser().resolve()
    grouped: dict[str, list[dict[str, str]]] = {}
    for item in copied_assets:
        item_key = item.get("item_key") or item.get("label") or "manual-assets"
        grouped.setdefault(item_key, []).append(item)
    payload = {
        "schema_version": 1,
        "manifest_path": str(Path(manifest_path).expanduser().resolve()) if manifest_path else "",
        "assets_dir": str(assets_dir) if assets_dir else "",
        "copied_assets": copied_assets,
        "items": grouped,
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def maybe_create_stub(path: Path, title: str, create: bool, overwrite: bool) -> bool:
    if not create:
        return False
    if path.exists() and not overwrite:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"# {title}\n", encoding="utf-8")
    return True


def main() -> int:
    args = parse_args()

    request_date = normalize_date(args.date)
    article_name = article_base_name(args.article_filename, args.keep_extension)
    safe_article_name = sanitize_filename_part(article_name)
    note_title = (
        args.note_title.strip()
        if args.note_title
        else safe_article_name
        if args.no_title_prefix
        else f"{NOTE_TITLE_PREFIX}{safe_article_name}"
    )
    note_filename = normalize_note_filename(args.note_filename, article_name)

    current_dir = Path(args.current_dir).expanduser().resolve()

    zotero_note_path = None
    zotero_stub_created = False
    if not args.no_zotero_file:
        if args.zotero_note_path:
            zotero_note_path = normalize_markdown_path(args.zotero_note_path)
        else:
            current_dir.mkdir(parents=True, exist_ok=True)
            zotero_note_path = current_dir / note_filename
        zotero_stub_created = maybe_create_stub(
            zotero_note_path, note_title, args.create_note_stubs, args.overwrite_stubs
        )

    obsidian_note_path = None
    obsidian_assets_dir = None
    copied_assets: list[dict[str, str]] = []
    copy_map_path = None
    obsidian_stub_created = False
    if not args.no_obsidian:
        if args.obsidian_note_path:
            obsidian_note_path = normalize_markdown_path(args.obsidian_note_path)
            obsidian_date_dir = obsidian_note_path.parent
            obsidian_vault = None
        elif args.obsidian_dir:
            obsidian_date_dir = Path(args.obsidian_dir).expanduser().resolve()
            obsidian_vault = None
        else:
            obsidian_vault = Path(args.obsidian_vault).expanduser().resolve()
            obsidian_date_dir = obsidian_vault / "组会分享" / request_date
        obsidian_assets_dir = obsidian_date_dir / "assets"
        obsidian_assets_dir.mkdir(parents=True, exist_ok=True)
        if obsidian_note_path is None:
            obsidian_note_path = obsidian_date_dir / note_filename
        obsidian_stub_created = maybe_create_stub(
            obsidian_note_path, note_title, args.create_note_stubs, args.overwrite_stubs
        )
        copied_assets = copy_assets(
            iter_asset_files(args.asset, args.asset_dir), obsidian_assets_dir
        )
        if args.sync_from_manifest:
            manifest_copied = sync_assets_from_manifest(
                args.sync_from_manifest,
                obsidian_assets_dir,
                article_name,
            )
            copied_assets.extend(manifest_copied)
        if args.copy_map:
            copy_map_path = Path(args.copy_map).expanduser().resolve()
            write_copy_map(args.copy_map, args.sync_from_manifest, obsidian_assets_dir, copied_assets)

    result = {
        "note_title": note_title,
        "note_filename": note_filename,
        "request_date": request_date,
        "paper_name": safe_article_name,
        "zotero_note_path": str(zotero_note_path) if zotero_note_path else None,
        "zotero_stub_created": zotero_stub_created,
        "obsidian_vault": str(obsidian_vault) if not args.no_obsidian and obsidian_vault else None,
        "obsidian_output_dir": str(obsidian_note_path.parent) if obsidian_note_path else None,
        "obsidian_note_path": str(obsidian_note_path) if obsidian_note_path else None,
        "obsidian_assets_dir": str(obsidian_assets_dir) if obsidian_assets_dir else None,
        "obsidian_stub_created": obsidian_stub_created,
        "copied_assets": copied_assets,
        "copy_map_path": str(copy_map_path) if copy_map_path else None,
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
